
import { GoogleGenAI, Modality } from "@google/genai";
import { Language } from "../types";

/**
 * Converts the raw base64 string (which might include the data URL prefix)
 * into just the base64 data.
 */
const stripBase64Prefix = (base64Str: string) => {
  return base64Str.replace(/^data:image\/\w+;base64,/, "");
};

const getMimeType = (base64Str: string) => {
  const match = base64Str.match(/^data:(image\/\w+);base64,/);
  return match ? match[1] : "image/png";
};

/**
 * Generates the visual technical drawing.
 * Uses flash by default, or pro for high quality requests.
 */
export const generateTechnicalDrawingImage = async (
  apiKey: string,
  imageBase64: string,
  highQuality: boolean = false,
  includeDimensions: boolean = true
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey });
  
  const model = highQuality ? 'gemini-3-pro-image-preview' : 'gemini-2.5-flash-image';
  
  const dimensionInstruction = includeDimensions 
    ? "Add sophisticated technical dimension lines with arrows, ensuring they are perfectly aligned with the object's geometry."
    : "STRICT REQUIREMENT: DO NOT add any dimension lines, measurements, arrows, text, or labels. Provide only the clean geometric design of the object.";

  // Prompt engineered for line art extraction
  const prompt = highQuality 
    ? `
    Act as a master technical illustrator. Transform this product photo into an ULTRA-HIGH-PRECISION technical line drawing.
    Technical Requirements:
    1. Pure white background (#FFFFFF).
    2. Razor-sharp, perfectly clean black vector-style lines.
    3. Use variable line weights: thicker for outer contours, thinner for internal details.
    4. NO shading, NO textures, NO shadows.
    5. ${dimensionInstruction}
    6. Ensure every minor detail of the product is captured with geometric perfection.
    7. Style: High-end industrial design blueprint / Patent application illustration.
    `
    : `
    Transform this product image into a professional technical line drawing (vector style).
    Requirements:
    1. White background.
    2. Clean, precise black lines.
    3. No shading or shadows.
    4. ${includeDimensions ? "Add technical dimension lines." : "Do NOT add any dimensions or text."}
    5. Maintain exact geometric proportions.
    6. Style: Engineering diagram.
  `;

  const base64Data = stripBase64Prefix(imageBase64);
  const mimeType = getMimeType(imageBase64);

  try {
    const config: any = {
      responseModalities: [Modality.IMAGE],
    };

    if (highQuality) {
      config.imageConfig = {
        aspectRatio: "1:1",
        imageSize: "2K"
      };
    }

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: config,
    });

    // Extract image - check all parts as per guidelines
    const candidates = response.candidates?.[0]?.content?.parts || [];
    for (const part of candidates) {
      if (part.inlineData && part.inlineData.data) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the model.");

  } catch (error) {
    console.error("Image Generation Error:", error);
    throw error;
  }
};

/**
 * Generates the step-by-step textual analysis plan using gemini-2.5-flash
 */
export const generateTechnicalPlan = async (
  apiKey: string,
  imageBase64: string,
  language: Language = 'en'
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey });

  const base64Data = stripBase64Prefix(imageBase64);
  const mimeType = getMimeType(imageBase64);

  const languageInstruction = language === 'ar' 
    ? "Output the response in Arabic language. Use technical Arabic terminology suitable for engineering." 
    : "Output the response in English.";

  const systemInstruction = `
    Act like a senior graphic designer and technical illustrator.
    Your goal is to analyze the provided product photo and output a structured plan for converting it into a technical drawing.
    Format the output as a structured, step-by-step markdown list.
    Include:
    1. Extraction Steps (identifying shapes).
    2. Drawing Steps (outlines, details).
    3. Measurement Placement (where to put dimensions).
    4. Quality Check (tolerances, clarity).
    ${languageInstruction}
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: "Provide the technical illustration plan for this object.",
          },
        ],
      },
      config: {
        systemInstruction: systemInstruction,
      },
    });

    return response.text || "No analysis provided.";
  } catch (error) {
    console.error("Text Analysis Error:", error);
    throw error;
  }
};
